import type { AestheticMockResult, ExperienceMockResult, ExperienceModelOption, RoiInput } from './types'

export const DEFAULT_ROIS: RoiInput[] = [
  { id: 'search', label: '顶部频道与搜索区', x: 0.02, y: 0.07, width: 0.96, height: 0.1 },
  { id: 'product', label: '商品流首屏', x: 0.02, y: 0.6, width: 0.96, height: 0.28 },
]

const JD_NEW_ARRIVALS_REGIONS = [
  {
    id: 'search',
    label: '顶部频道与搜索区',
    x: 2,
    y: 7,
    width: 96,
    height: 10,
    score: 86,
    note: '频道高亮和搜索框边界清楚，是当前首屏最稳定的任务入口。',
  },
  {
    id: 'entry-nav',
    label: '新品功能入口区',
    x: 2,
    y: 17,
    width: 96,
    height: 8,
    score: 78,
    note: '入口语义明确，但一屏可见入口偏多，后续入口被截断。',
  },
  {
    id: 'promo-cluster',
    label: '首屏活动区',
    x: 2,
    y: 25,
    width: 96,
    height: 25,
    score: 72,
    note: '主促销、抽签、抢新同时出现，活动感强但主次竞争明显。',
  },
  {
    id: 'season-banner',
    label: '紫色活动横幅',
    x: 4,
    y: 50,
    width: 92,
    height: 7,
    score: 69,
    note: '横幅有跳出度，但与上下内容割裂，像插入广告位。',
  },
  {
    id: 'product-grid',
    label: '商品流首屏',
    x: 2,
    y: 60,
    width: 96,
    height: 28,
    score: 74,
    note: '商品图吸引力强，左侧粉色鞋形成第一视觉记忆点。',
  },
  {
    id: 'red-packet',
    label: '红包浮层',
    x: 77,
    y: 69,
    width: 19,
    height: 12,
    score: 62,
    note: '高饱和红色强于商品主体，可能干扰商品识别。',
  },
]

export const AESTHETIC_MOCK_RESULT: AestheticMockResult = {
  overallScore: 76,
  confidence: { level: '中高', score: 0.84, note: '固定样例用于验证报告结构，不代表真实图像算法置信度。' },
  summary: '页面具备强促销氛围和明确商品曝光能力，但视觉焦点过多，搜索、活动、商品卡和红包浮层同时抢占注意力。',
  metrics: [
    { label: '频道识别', value: 88 },
    { label: '搜索可见性', value: 85 },
    { label: '商品突出度', value: 79 },
    { label: '促销氛围', value: 91 },
    { label: '信息层级', value: 67 },
    { label: '色彩和谐度', value: 70 },
    { label: '注意力聚焦', value: 63 },
  ],
  imageStats: [
    { label: '主促销色', value: '红 / 粉 / 紫' },
    { label: '商品图占比', value: '34%' },
    { label: '首屏入口数', value: 13 },
    { label: '高饱和焦点', value: 5 },
    { label: '浮层干扰', value: '偏高' },
    { label: '视觉密度', value: '高' },
  ],
  roiResults: [
    { label: '顶部频道与搜索区', score: 86, brightness: 0.82, saturation: 0.48, attentionRank: 2 },
    { label: '首屏活动区', score: 72, brightness: 0.76, saturation: 0.66, attentionRank: 3 },
    { label: '商品流首屏', score: 74, brightness: 0.81, saturation: 0.7, attentionRank: 1 },
    { label: '红包浮层', score: 62, brightness: 0.78, saturation: 0.87, attentionRank: 4 },
  ],
  pairResult: [
    { label: '搜索框对比', value: '清晰' },
    { label: '主活动层级', value: '中等' },
    { label: '商品与浮层竞争', value: '偏强' },
    { label: '新品感一致性', value: '被促销稀释' },
  ],
  attention: {
    peak: 0.89,
    balance: 0.77,
    distraction: 0.24,
    heatmap: [
      0.08, 0.12, 0.18, 0.26, 0.32, 0.21, 0.14, 0.09,
      0.11, 0.2, 0.36, 0.58, 0.7, 0.42, 0.2, 0.12,
      0.14, 0.27, 0.54, 0.83, 0.92, 0.61, 0.28, 0.14,
      0.12, 0.25, 0.49, 0.72, 0.78, 0.55, 0.3, 0.16,
      0.08, 0.16, 0.28, 0.39, 0.45, 0.47, 0.5, 0.31,
      0.06, 0.12, 0.2, 0.29, 0.41, 0.62, 0.76, 0.42,
      0.05, 0.09, 0.16, 0.24, 0.35, 0.55, 0.68, 0.37,
      0.04, 0.07, 0.11, 0.16, 0.22, 0.31, 0.38, 0.21,
    ],
  },
  findings: [
    '顶部“新品”频道识别清楚，搜索框也足够明显，基础导航效率好。',
    '首屏活动模块过多，用户需要在新品推荐、抽签、抢新、拼团和红包之间连续判断。',
    '左侧粉色 adidas 商品形成强记忆点，右侧红包浮层比商品主体更抢眼。',
    '红、粉、紫、金共同出现，促销情绪强，但“新品发现”的频道气质被稀释。',
  ],
  recommendations: [
    '首屏保留一个主叙事，例如“新品首发”或“送礼上新季”，弱化并列活动入口。',
    '红包浮层建议缩小或移到商品卡外，避免压过右侧鞋款主体。',
    '频道入口区优先突出“新品推荐”“新奇集市”“送礼新品”三个核心入口。',
    '商品卡促销标签压缩为 1 到 2 个主标签，让品牌、价格和新品属性形成稳定阅读顺序。',
  ],
  boundaryNotes: ['演示数据来自固定 fixture。', '注意力示意不等同于真实眼动实验或用户行为数据。', '上传其他图片不会改变本案例报告的固定结论。'],
  caseStudy: {
    title: '京东 App 新品频道首页',
    pageType: '移动端电商频道首页',
    scenario: '用户进入“新品”频道后，浏览新品活动、抽签商品、上新商品流，并尝试搜索具体新品。',
    imageAlt: '京东 App 新品频道首页截图，包含顶部搜索、新品入口、促销卡片、商品流和底部导航',
    regions: JD_NEW_ARRIVALS_REGIONS,
    metrics: [
      { label: '频道识别', value: 88, note: '“新品”高亮清楚，用户能快速知道所在频道。' },
      { label: '搜索可见性', value: 85, note: '红色描边搜索框明显，适合作为主入口。' },
      { label: '商品突出度', value: 79, note: '鞋类商品图足够大，识别效率不错。' },
      { label: '促销氛围', value: 91, note: '红包、抽签、拼团、新品礼等活动感非常强。' },
      { label: '信息层级', value: 67, note: '活动、入口、商品、红包浮层同时竞争。' },
      { label: '注意力聚焦', value: 63, note: '多个高饱和焦点导致视线跳转频繁。' },
    ],
    attentionHotspots: [
      { label: '第一注意力峰值', value: '左下粉色 adidas 商品图', note: '大面积粉色和商品尺寸形成最强视觉记忆点。' },
      { label: '第二注意力峰值', value: '顶部搜索框与“新品”频道', note: '频道定位和任务入口仍然清楚。' },
      { label: '第三注意力峰值', value: '右侧“¥8.8 领红包”浮层', note: '激励入口非常抢眼，可能压过商品主体。' },
    ],
  },
}

export const EXPERIENCE_MODELS: ExperienceModelOption[] = [
  { id: 'heart', label: 'HEART', resultLabel: 'HEART 模型', description: '衡量满意度、参与、采纳、留存和任务成功。', bestFor: '版本体验指标与参与度评估' },
  { id: 'gsm', label: 'GSM', resultLabel: 'GSM 模型', description: '从目标、信号和指标建立衡量体系。', bestFor: '指标设计与实验评估' },
  { id: 'jtbd', label: 'JTBD', resultLabel: 'JTBD 模型', description: '围绕用户要完成的任务理解动机。', bestFor: '需求探索与机会识别' },
  { id: 'kano', label: 'Kano', resultLabel: 'Kano 模型', description: '区分基本型、期望型与兴奋型需求。', bestFor: '功能取舍与需求排序' },
  { id: 'sus', label: 'SUS', resultLabel: 'SUS 模型', description: '快速评估系统整体可用性。', bestFor: '可用性基线与版本对比' },
  { id: 'nps', label: 'NPS', resultLabel: 'NPS 模型', description: '以推荐意愿观察忠诚与口碑。', bestFor: '品牌口碑与忠诚度' },
  { id: 'tam', label: 'TAM', resultLabel: 'TAM 模型', description: '分析感知有用性、易用性和技术接受度。', bestFor: 'AI 功能与新技术采纳' },
  { id: 'cognitive_load', label: '认知负荷', resultLabel: '认知负荷理论', description: '观察复杂度、学习成本和认知压力。', bestFor: '复杂页面与信息架构' },
  { id: 'aesthetic_usability', label: '美学可用性', resultLabel: '美学可用性效应', description: '解释视觉观感对易用性感知的影响。', bestFor: '视觉设计与品牌感知' },
  { id: 'fogg', label: 'Fogg', resultLabel: 'Fogg 行为模型', description: '从动机、能力与触发解释行为。', bestFor: '转化优化与行为引导' },
]

export const EXPERIENCE_MOCK_RESULT: ExperienceMockResult = {
  summary: '建议组合使用 HEART 衡量频道结果，GSM 拆解目标、信号和指标，并用认知负荷与 Fogg 行为模型验证促销触发是否干扰商品理解。',
  frameworkSummary: '先用 HEART 定义频道体验结果，再用 GSM 建立指标闭环，最后用认知负荷和 Fogg 判断首屏信息密度与红包、抽签等触发机制是否有效。',
  defaultModelIds: ['heart', 'gsm', 'cognitive_load'],
  reasons: {
    heart: ['研究问题同时涉及参与和任务成功。', '适合形成版本前后的体验指标基线。'],
    gsm: ['需要把“提升体验”拆成可观察信号。', '便于后续定义实验和追踪指标。'],
    jtbd: ['适合补充用户在首页场景中的真实任务。'],
    kano: ['适合判断首页改版能力的优先级。', '能区分必须满足和增益体验。'],
    sus: ['适合补充整体易用性基线。'],
    nps: ['适合长期口碑跟踪，但与当前页面任务距离较远。'],
    tam: ['当研究对象是新 AI 能力时更有价值。'],
    cognitive_load: ['页面信息密度高，需要判断用户是否能快速分辨主次。'],
    aesthetic_usability: ['可解释视觉质量对易用性感知的影响。'],
    fogg: ['页面大量使用红包、抽签、限量、抢新等行为触发机制。'],
  },
  warnings: ['本结果未读取真实业务数据，也未执行用户调研。'],
  boundaryNotes: ['演示推荐来自前端固定规则和 fixture。', '方法资料仅展示索引名称，不代表已核验 PDF 正文。', '真实结论需要埋点、可用性测试或 A/B 实验验证。'],
  caseStudy: {
    title: '京东 App 新品频道首页',
    pageType: '移动端电商频道首页',
    question: '如何判断“新品频道首页”是否能让用户快速理解新品价值，并有效推动浏览、搜索、抽签、领券和商品点击？',
    scenario: '截图显示搜索、频道入口、促销卡片、红包浮层和商品流同时出现在首屏，是典型高密度电商频道体验问题。',
    imageAlt: '京东 App 新品频道首页截图，用于体验模型推荐演示',
    regions: JD_NEW_ARRIVALS_REGIONS.filter((region) => region.id !== 'season-banner'),
    hypotheses: [
      '如果顶部搜索和频道标题足够清晰，用户能快速确认自己处于“新品”场景。',
      '如果首屏促销入口过多，用户会更容易浏览，但更难判断哪个入口最重要。',
      '如果红包浮层强于商品主体，用户可能点击激励入口，而不是理解商品价值。',
      '如果商品卡标签过多，用户会依赖价格和图片快速扫视，忽略新品卖点。',
      '如果“新品”频道的视觉语言被红包、拼团、抽奖稀释，用户会把它理解成普通促销页。',
    ],
    gsmGoals: [
      { goal: '快速理解新品频道', signals: '频道标题识别、搜索框使用、频道入口点击', metrics: '3 秒识别率、搜索框点击率、顶部入口点击分布' },
      { goal: '提升新品商品浏览效率', signals: '继续滑动、商品点击、收藏或加购', metrics: '首屏商品点击率、商品流滑动深度、商品卡点击深度' },
      { goal: '验证促销触发是否干扰', signals: '红包点击、抽签点击、商品点击之间的关系', metrics: '红包点击率、商品点击率、红包点击后商品转化率' },
      { goal: '降低首屏理解负担', signals: '用户能否说出主活动、主入口和主商品', metrics: '5 秒理解测试通过率、任务完成时间、误点率' },
    ],
    heartMetrics: [
      { dimension: 'Happiness', metrics: '新品频道满意度、页面清晰度评分' },
      { dimension: 'Engagement', metrics: '首屏入口点击、商品流滑动深度、活动参与次数' },
      { dimension: 'Adoption', metrics: '首次使用搜索、抽签、领券、新品推荐入口比例' },
      { dimension: 'Retention', metrics: '次日或下周再次访问新品频道比例' },
      { dimension: 'Task success', metrics: '找到感兴趣新品、完成商品点击、完成加购或关注的比例' },
    ],
    researchQuestions: [
      '用户进入页面 3 秒内，能否准确说出当前页面主要任务是“发现新品”还是“领取促销”？',
      '用户最先注意到的是顶部搜索、TF 活动卡、粉色鞋商品，还是红包浮层？',
      '用户是否能区分“新品推荐”“新奇集市”“送礼新品”“PLUS 新享”这些入口的差异？',
      '红包浮层是否提高行动意愿，还是干扰商品理解？',
      '用户在商品卡中主要依赖什么做判断：品牌、图片、价格、促销标签，还是新品属性？',
    ],
    experiments: [
      { name: 'A 方案', description: '维持当前强促销结构，观察活动点击与商品点击的关系。' },
      { name: 'B 方案', description: '弱化红包浮层，突出新品推荐和商品主体。' },
      { name: 'C 方案', description: '减少首屏活动入口，把“新品首发”作为唯一主叙事。' },
    ],
  },
}
